name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: 20.193.153.165
          username: SSH_USERNAME
          key: SSH_PRIVATE_KEY
          source: "./*"
          target: "/var/www/html"

